import os
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table, TableStyle, KeepTogether, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.lib.units import inch
from typing import Dict, Any, List

# Define Brand Colors
BRAND_NAVY = colors.HexColor("#0f172a")
BRAND_SLATE = colors.HexColor("#334155")
BRAND_GRAY = colors.HexColor("#94a3b8")
BRAND_LIGHT_GRAY = colors.HexColor("#f1f5f9")
BRAND_WHITE = colors.white
BRAND_GREEN = colors.HexColor("#166534")
BRAND_RED = colors.HexColor("#991b1b")
BRAND_YELLOW = colors.HexColor("#854d0e")

class FintechDocTemplate(BaseDocTemplate):
    def __init__(self, filename, **kw):
        super().__init__(filename, **kw)
        
        # Frame for content
        frame = Frame(inch, inch, self.pagesize[0] - 2*inch, self.pagesize[1] - 2*inch, id='normal')
        
        # Add PageTemplate
        template = PageTemplate(id='FintechLayout', frames=frame, onPage=self._header_footer)
        self.addPageTemplates([template])

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        
        # Header
        canvas.setFont("Helvetica-Bold", 10)
        canvas.setFillColor(BRAND_NAVY)
        canvas.drawString(inch, self.pagesize[1] - 0.5 * inch, "REPRESENTAI")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(BRAND_GRAY)
        canvas.drawRightString(self.pagesize[0] - inch, self.pagesize[1] - 0.5 * inch, "CONFIDENTIAL DISPUTE DOCUMENT")
        
        # Header Line
        canvas.setStrokeColor(BRAND_LIGHT_GRAY)
        canvas.setLineWidth(1)
        canvas.line(inch, self.pagesize[1] - 0.6 * inch, self.pagesize[0] - inch, self.pagesize[1] - 0.6 * inch)
        
        # Footer
        canvas.setStrokeColor(BRAND_LIGHT_GRAY)
        canvas.line(inch, 0.6 * inch, self.pagesize[0] - inch, 0.6 * inch)
        
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(BRAND_GRAY)
        canvas.drawString(inch, 0.4 * inch, "Generated by RepresentAI Deterministic Engine")
        canvas.drawRightString(self.pagesize[0] - inch, 0.4 * inch, f"Page {doc.page}")
        
        canvas.restoreState()

def create_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='FintechTitle', fontName='Helvetica-Bold', fontSize=18, textColor=BRAND_NAVY, spaceAfter=20))
    styles.add(ParagraphStyle(name='FintechH1', fontName='Helvetica-Bold', fontSize=14, textColor=BRAND_NAVY, spaceBefore=20, spaceAfter=10))
    styles.add(ParagraphStyle(name='FintechH2', fontName='Helvetica-Bold', fontSize=12, textColor=BRAND_SLATE, spaceBefore=15, spaceAfter=8))
    styles.add(ParagraphStyle(name='FintechBody', fontName='Helvetica', fontSize=10, textColor=BRAND_SLATE, leading=14, spaceAfter=8))
    styles.add(ParagraphStyle(name='FintechBodyBold', fontName='Helvetica-Bold', fontSize=10, textColor=BRAND_NAVY, leading=14, spaceAfter=8))
    styles.add(ParagraphStyle(name='TimelineEvent', fontName='Helvetica', fontSize=9, textColor=BRAND_SLATE, leading=12))
    styles.add(ParagraphStyle(name='VerdictFIGHT', fontName='Helvetica-Bold', fontSize=14, textColor=BRAND_GREEN, alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='VerdictACCEPT', fontName='Helvetica-Bold', fontSize=14, textColor=BRAND_RED, alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='VerdictREVIEW', fontName='Helvetica-Bold', fontSize=14, textColor=BRAND_YELLOW, alignment=TA_CENTER))
    return styles

def get_recommendation_style(decision: str, styles):
    decision_upper = decision.upper() if decision else "UNKNOWN"
    if "FIGHT" in decision_upper:
        return styles['VerdictFIGHT'], BRAND_GREEN
    elif "ACCEPT" in decision_upper:
        return styles['VerdictACCEPT'], BRAND_RED
    else:
        return styles['VerdictREVIEW'], BRAND_YELLOW

def _format_currency(amount_in_paise: int, currency: str = "INR") -> str:
    amount = amount_in_paise / 100
    if currency.upper() == "INR":
        return f"Rs. {amount:,.2f}"
    elif currency.upper() == "USD":
        return f"${amount:,.2f}"
    return f"{amount:,.2f} {currency}"

def generate_dispute_response_pdf(investigation: Dict[str, Any], evidence_claims: List[Dict[str, Any]], dispute: Dict[str, Any], output_path: str):
    """
    Generate a premium, multi-page fintech dispute PDF.
    """
    doc = FintechDocTemplate(output_path, pagesize=letter)
    styles = create_styles()
    Story = []
    
    # ---------------- PAGE 1: EXECUTIVE SUMMARY ---------------- #
    
    Story.append(Paragraph("DISPUTE REPRESENTMENT PACKAGE", styles['FintechTitle']))
    
    # Dispute Overview Block
    overview_data = [
        ["DISPUTE ID", dispute.get('razorpay_dispute_id', 'N/A')],
        ["AMOUNT", _format_currency(dispute.get('amount', 0), dispute.get('currency', 'INR'))],
        ["REASON", str(dispute.get('reason_code', 'N/A')).replace('_', ' ').title()],
        ["STATUS", str(dispute.get('status', 'N/A')).upper()]
    ]
    
    t_overview = Table(overview_data, colWidths=[1.5*inch, 4*inch])
    t_overview.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), BRAND_GRAY),
        ('TEXTCOLOR', (1, 0), (1, -1), BRAND_NAVY),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    Story.append(t_overview)
    Story.append(Spacer(1, 15))
    
    # Executive Summary
    Story.append(Paragraph("EXECUTIVE SUMMARY", styles['FintechH1']))
    Story.append(Paragraph("The merchant contests this dispute based on verified delivery, order, and communication evidence. All claims below have been deterministically validated against raw data sources.", styles['FintechBody']))
    
    reasoning = investigation.get('reasoning_summary', '')
    if reasoning:
        Story.append(Paragraph(reasoning, styles['FintechBody']))
        
    Story.append(Spacer(1, 15))
    
    # Evidence Strength Metrics
    verified_claims = [e for e in evidence_claims if e.get('verified') is True]
    unsupported_claims = [e for e in evidence_claims if e.get('verified') is not True]
    
    metrics_data = [
        ["VERIFIED CLAIMS", str(len(verified_claims))],
        ["UNSUPPORTED/REJECTED", str(len(unsupported_claims))]
    ]
    
    t_metrics = Table(metrics_data, colWidths=[2.5*inch, 1*inch])
    t_metrics.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), BRAND_SLATE),
        ('TEXTCOLOR', (1, 0), (1, -1), BRAND_NAVY),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BACKGROUND', (0, 0), (-1, -1), BRAND_LIGHT_GRAY),
        ('BOX', (0, 0), (-1, -1), 1, BRAND_LIGHT_GRAY),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    Story.append(t_metrics)
    Story.append(Spacer(1, 25))
    
    # Recommendation Box
    decision = str(investigation.get('decision', 'HUMAN_REVIEW'))
    confidence = investigation.get('confidence', 0.0)
    verdict_style, verdict_color = get_recommendation_style(decision, styles)
    
    rec_data = [
        [Paragraph("AI RECOMMENDATION", styles['FintechBodyBold'])],
        [Paragraph(f"{decision.replace('_', ' ')}", verdict_style)],
        [Paragraph(f"Confidence Score: {confidence*100:.1f}%", styles['FintechBody'])]
    ]
    t_rec = Table(rec_data, colWidths=[5.5*inch])
    t_rec.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 1.5, verdict_color),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))
    Story.append(t_rec)
    
    Story.append(PageBreak())
    
    # ---------------- PAGE 2: TIMELINE & EVIDENCE ---------------- #
    
    Story.append(Paragraph("INVESTIGATION TIMELINE", styles['FintechH1']))
    completed_at = investigation.get("completed_at", "Unknown")
    
    timeline_data = [
        ["→", "Dispute Created", "Verified"],
        ["→", "Investigation Started", "Verified"],
        ["→", "Evidence Collected", "Verified"],
        ["→", "Gemini Analysis Completed", "Verified"],
        ["→", "Evidence Validation Completed", "Verified"],
        ["→", "Recommendation Generated", str(completed_at)[:19].replace('T', ' ')]
    ]
    t_timeline = Table(timeline_data, colWidths=[0.3*inch, 3*inch, 2.2*inch])
    t_timeline.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (-1, -1), BRAND_SLATE),
        ('TEXTCOLOR', (2, 0), (2, -1), BRAND_GRAY),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    Story.append(t_timeline)
    Story.append(Spacer(1, 20))
    
    Story.append(Paragraph("KEY EVIDENCE", styles['FintechH1']))
    
    # Group ONLY verified claims by source
    grouped_evidence = {}
    for ev in verified_claims:
        src = str(ev.get("source", "Other")).title()
        if src not in grouped_evidence:
            grouped_evidence[src] = []
        grouped_evidence[src].append(ev)
        
    for source, claims in grouped_evidence.items():
        Story.append(Paragraph(f"{source.upper()} DETAILS", styles['FintechH2']))
        claim_data = []
        for claim in claims:
            c_text = Paragraph(str(claim.get("claim", "")), styles['FintechBody'])
            v_text = Paragraph(f"<b>{str(claim.get('value', ''))}</b>", styles['FintechBody'])
            claim_data.append([c_text, v_text])
            
        if claim_data:
            t_claims = Table(claim_data, colWidths=[2.5*inch, 3*inch])
            t_claims.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('LINEBELOW', (0, 0), (-1, -1), 0.5, BRAND_LIGHT_GRAY),
            ]))
            Story.append(t_claims)
            Story.append(Spacer(1, 10))
            
    Story.append(PageBreak())
    
    # ---------------- PAGE 3: FULL VERIFICATION TABLE ---------------- #
    
    Story.append(Paragraph("AI EVIDENCE VERIFICATION", styles['FintechH1']))
    Story.append(Paragraph("Complete record of all claims evaluated by the AI, including those rejected during deterministic validation.", styles['FintechBody']))
    Story.append(Spacer(1, 10))
    
    header = [
        Paragraph("<b>Claim</b>", styles['FintechBodyBold']), 
        Paragraph("<b>Source</b>", styles['FintechBodyBold']), 
        Paragraph("<b>Result</b>", styles['FintechBodyBold']),
        Paragraph("<b>Value</b>", styles['FintechBodyBold'])
    ]
    verification_data = [header]
    
    for ev in evidence_claims:
        is_verified = ev.get('verified') is True
        result_text = "VERIFIED" if is_verified else "REJECTED / UNSUPPORTED"
        result_color = BRAND_GREEN if is_verified else BRAND_RED
        
        c_text = Paragraph(str(ev.get('claim', '')), styles['FintechBody'])
        s_text = Paragraph(str(ev.get('source', '')), styles['FintechBody'])
        r_text = Paragraph(f"<font color='{result_color.hexval()}'><b>{result_text}</b></font>", styles['FintechBody'])
        v_text = Paragraph(str(ev.get('value', 'N/A')), styles['FintechBody'])
        
        verification_data.append([c_text, s_text, r_text, v_text])
        
    t_ver = Table(verification_data, colWidths=[2*inch, 1*inch, 1.2*inch, 1.3*inch])
    t_ver.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (-1, 0), 1, BRAND_NAVY),
        ('LINEBELOW', (0, 1), (-1, -1), 0.5, BRAND_LIGHT_GRAY),
    ]))
    Story.append(t_ver)
    
    doc.build(Story)
    return output_path
