import Link from "next/link";

export function ProductPreview() {
  return (
    <section className="py-24 bg-background overflow-hidden relative">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-[600px] bg-primary/5 rounded-full blur-[100px] pointer-events-none"></div>
      
      <div className="max-w-7xl mx-auto px-6 md:px-12 text-center relative z-10">
        <h2 className="font-display-md text-display-md font-bold text-on-surface mb-16">
          The Investigation Command Center
        </h2>
        
        {/* Abstract UI Mockup */}
        <div className="relative mx-auto max-w-5xl bg-surface-container-lowest border border-outline-variant rounded-2xl shadow-2xl overflow-hidden">
          <div className="h-12 bg-surface-container-low border-b border-outline-variant flex items-center px-4 gap-4">
            <div className="flex gap-2">
              <div className="w-3 h-3 rounded-full bg-outline-variant"></div>
              <div className="w-3 h-3 rounded-full bg-outline-variant"></div>
              <div className="w-3 h-3 rounded-full bg-outline-variant"></div>
            </div>
            <div className="h-6 w-64 bg-surface-container-highest rounded mx-auto opacity-50"></div>
          </div>
          <div className="p-8 grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
            <div className="col-span-2 flex flex-col gap-6">
              <div className="h-32 bg-surface-container-low rounded border border-outline-variant"></div>
              <div className="h-64 bg-surface-container-low rounded border border-outline-variant"></div>
            </div>
            <div className="flex flex-col gap-6">
              <div className="h-48 bg-primary/5 border border-primary/20 rounded"></div>
              <div className="h-48 bg-surface-container-low rounded border border-outline-variant"></div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export function PdfSection() {
  return (
    <section className="py-24 bg-background">
      <div className="max-w-7xl mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
        {/* PDF Visual */}
        <div className="relative aspect-[3/4] bg-white rounded shadow-[0_20px_60px_-15px_rgba(0,0,0,0.3)] p-8 font-serif text-black border border-gray-200 transform -rotate-2 hover:rotate-0 transition-transform duration-500">
          <div className="border-b-2 border-black pb-4 mb-6">
            <h3 className="text-2xl font-bold uppercase tracking-widest">Representment Package</h3>
            <p className="text-gray-500 text-sm font-sans mt-2">Dispute ID: disp_8F21 • Generated by RepresentAI</p>
          </div>
          <div className="space-y-4 text-sm leading-relaxed">
            <div className="bg-gray-100 p-4 font-sans font-bold text-lg mb-6">RECOMMENDATION: FIGHT DISPUTE</div>
            <p><strong>Reason Code:</strong> Goods/Services Not Received</p>
            <p><strong>Amount:</strong> ₹50,000</p>
            <p className="border-l-4 border-gray-300 pl-4 italic text-gray-600 my-4">
              "Based on the validated evidence, the item was successfully delivered to the customer's verified address and signed for by the cardholder."
            </p>
            <div className="h-px bg-gray-200 my-4"></div>
            <p className="font-bold">Verified Evidence Timeline:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Aug 21: Order placed via verified IP.</li>
              <li>Aug 22: Payment captured successfully.</li>
              <li>Aug 24: Item delivered and signed for.</li>
            </ul>
          </div>
        </div>

        <div>
          <h2 className="font-display-md text-display-md font-bold text-on-surface mb-6">
            Prepared for submission.
          </h2>
          <p className="font-body-lg text-body-lg text-on-surface-variant mb-6">
            The investigation concludes with a structured response package. RepresentAI compiles validated evidence, reasoning summaries, and timeline data into a professional PDF document.
          </p>
          <p className="font-body-md text-body-md text-on-surface-variant mb-8">
            This document is prepared specifically for integration into your existing payment/dispute workflow (e.g., Razorpay dashboard) after human approval.
          </p>
          <button disabled className="bg-surface-container-highest text-on-surface-variant px-6 py-3 rounded font-label-md flex items-center gap-2 opacity-50 cursor-not-allowed border border-outline-variant">
            <span className="material-symbols-outlined">download</span>
            Download Evidence Package
          </button>
          <p className="text-xs text-on-surface-variant mt-2">Available within the Dashboard after an investigation.</p>
        </div>
      </div>
    </section>
  );
}

export function SecuritySection() {
  return (
    <section id="security" className="py-24 bg-surface-container-lowest border-y border-outline-variant">
      <div className="max-w-7xl mx-auto px-6 md:px-12 text-center">
        <h2 className="font-display-md text-display-md font-bold text-on-surface mb-16">Enterprise Safeguards</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 text-left">
          <div>
            <span className="material-symbols-outlined text-primary mb-4 text-[32px]">shield</span>
            <h3 className="font-headline-sm font-bold text-on-surface mb-2">Deterministic Validation</h3>
            <p className="font-body-sm text-on-surface-variant">AI hallucinations are structurally prevented. Generated claims are algorithmically verified against API source data.</p>
          </div>
          <div>
            <span className="material-symbols-outlined text-primary mb-4 text-[32px]">fact_check</span>
            <h3 className="font-headline-sm font-bold text-on-surface mb-2">Source-Grounded</h3>
            <p className="font-body-sm text-on-surface-variant">Every piece of evidence in the final package retains a cryptographic link to its original system source record.</p>
          </div>
          <div>
            <span className="material-symbols-outlined text-primary mb-4 text-[32px]">gavel</span>
            <h3 className="font-headline-sm font-bold text-on-surface mb-2">Human Approval</h3>
            <p className="font-body-sm text-on-surface-variant">The AI recommends, but humans decide. No evidence package is submitted without explicit merchant authorization.</p>
          </div>
          <div>
            <span className="material-symbols-outlined text-primary mb-4 text-[32px]">history</span>
            <h3 className="font-headline-sm font-bold text-on-surface mb-2">Full Auditability</h3>
            <p className="font-body-sm text-on-surface-variant">Every stage of the investigation, from data retrieval to final decision, is recorded in an immutable audit log.</p>
          </div>
        </div>
      </div>
    </section>
  );
}

export function Footer() {
  return (
    <footer className="bg-background py-16 border-t border-outline-variant">
      <div className="max-w-7xl mx-auto px-6 md:px-12 grid grid-cols-1 md:grid-cols-4 gap-12">
        <div className="col-span-1 md:col-span-2">
          <div className="flex items-center gap-2 mb-6">
            <div className="w-6 h-6 rounded bg-primary flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-white text-[14px]" style={{ fontVariationSettings: "'FILL' 1" }}>account_balance</span>
            </div>
            <span className="font-headline-sm font-bold text-on-surface">RepresentAI</span>
          </div>
          <p className="font-body-sm text-on-surface-variant max-w-sm">
            Turn dispute investigation from manual work into an evidence-driven workflow.
          </p>
        </div>
        
        <div>
          <h4 className="font-label-md font-bold text-on-surface mb-4">Product</h4>
          <ul className="space-y-3 font-body-sm text-on-surface-variant">
            <li><Link href="#how-it-works" className="hover:text-primary">How It Works</Link></li>
            <li><Link href="#evidence" className="hover:text-primary">Evidence</Link></li>
            <li><Link href="#benchmark" className="hover:text-primary">Benchmark</Link></li>
          </ul>
        </div>
        
        <div>
          <h4 className="font-label-md font-bold text-on-surface mb-4">Resources</h4>
          <ul className="space-y-3 font-body-sm text-on-surface-variant">
            <li><span className="text-primary font-medium">Demo Environment</span></li>
            <li><a href="#" className="hover:text-primary">Documentation</a></li>
            <li><a href="#" className="hover:text-primary">GitHub</a></li>
          </ul>
        </div>
      </div>
      <div className="max-w-7xl mx-auto px-6 md:px-12 mt-16 pt-8 border-t border-outline-variant flex justify-between items-center text-xs text-on-surface-variant">
        <p>&copy; 2026 RepresentAI. Hackathon Prototype.</p>
      </div>
    </footer>
  );
}
